from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.build_confirmatory_v3_config import (
    CONFIRMATORY_EXPERIMENT,
    build_confirmatory_config,
    evaluate_promotion,
)


def test_evaluate_promotion_enforces_thresholds() -> None:
    decision = evaluate_promotion(
        {"objective": {"score": 0.27, "sign_match_count": 4}},
        min_score=0.0,
        min_sign_matches=3,
    )
    assert decision == {
        "launched": True,
        "reason": None,
        "score": 0.27,
        "sign_match_count": 4,
    }

    rejected = evaluate_promotion(
        {"objective": {"score": 0.02, "sign_match_count": 2}},
        min_score=0.05,
        min_sign_matches=3,
    )
    assert rejected["launched"] is False
    assert rejected["reason"] == "best candidate did not clear promotion threshold"


def test_build_confirmatory_config_promotes_best_candidate() -> None:
    base_cfg = {
        "experiment": "causal_state_benchmark_v2",
        "run_name": "placeholder",
        "seed": 42,
        "model": {"name": "mistralai/Mistral-7B-v0.1", "device": "cuda"},
        "params": {
            "source_layer": 27,
            "window": 16,
            "holdout_per_group": 10,
            "generation_seeds": [101, 202],
            "bootstrap_resamples": 2000,
            "interventions": [{"name": "none", "alpha": 0.0}],
        },
        "results": {"root": "results", "phase": "phase1_mechanism"},
    }
    best_candidate = {
        "source_layer": 25,
        "window": 32,
        "alpha": 3.0,
        "objective": {"score": 0.27389, "sign_match_count": 4},
    }

    cfg = build_confirmatory_config(
        best_candidate=best_candidate,
        best_candidate_path="results/.../best_candidate.json",
        base_cfg=base_cfg,
        holdout_per_group=12,
        bootstrap_resamples=4000,
        generation_seeds=[101, 202, 303, 404],
        seed=314,
    )

    assert cfg["experiment"] == CONFIRMATORY_EXPERIMENT
    assert cfg["run_name"] == "mistral_l25_w32_a3_state_benchmark_v3_confirmatory"
    assert cfg["seed"] == 314
    assert cfg["params"]["source_layer"] == 25
    assert cfg["params"]["window"] == 32
    assert cfg["params"]["holdout_per_group"] == 12
    assert cfg["params"]["generation_seeds"] == [101, 202, 303, 404]
    assert cfg["params"]["bootstrap_resamples"] == 4000
    assert cfg["params"]["interventions"] == [
        {"name": "away_alpha_best", "alpha": -3.0},
        {"name": "none", "alpha": 0.0},
        {"name": "toward_alpha_best", "alpha": 3.0},
    ]
    assert cfg["autogenerated_from"]["objective_score"] == 0.27389


def test_build_confirmatory_config_is_json_roundtrippable(tmp_path: Path) -> None:
    cfg = build_confirmatory_config(
        best_candidate={
            "source_layer": 29,
            "window": 8,
            "alpha": 2.0,
            "objective": {"score": 0.11, "sign_match_count": 3},
        },
        best_candidate_path="candidate.json",
        base_cfg={
            "experiment": "causal_state_benchmark_v2",
            "run_name": "base",
            "model": {"name": "mistralai/Mistral-7B-v0.1", "device": "cuda"},
            "params": {},
            "results": {"root": "results", "phase": "phase1_mechanism"},
        },
        holdout_per_group=9,
        bootstrap_resamples=1500,
        generation_seeds=[7, 8],
        seed=99,
    )

    path = tmp_path / "cfg.json"
    path.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    loaded = json.loads(path.read_text(encoding="utf-8"))
    assert loaded["experiment"] == CONFIRMATORY_EXPERIMENT
    assert loaded["params"]["source_layer"] == 29
