from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _format_alpha(alpha: float) -> str:
    if abs(alpha - round(alpha)) < 1e-9:
        return str(int(round(alpha)))
    return str(alpha).replace(".", "p")


CONFIRMATORY_EXPERIMENT = "causal_state_benchmark_v3_confirmatory"


def evaluate_promotion(best_candidate: dict[str, Any], *, min_score: float, min_sign_matches: int) -> dict[str, Any]:
    objective = best_candidate.get("objective") or {}
    score = float(objective.get("score") or 0.0)
    sign_match_count = int(objective.get("sign_match_count") or 0)
    promoted = score > float(min_score) and sign_match_count >= int(min_sign_matches)
    return {
        "launched": promoted,
        "reason": None if promoted else "best candidate did not clear promotion threshold",
        "score": score,
        "sign_match_count": sign_match_count,
    }


def build_confirmatory_config(
    *,
    best_candidate: dict[str, Any],
    best_candidate_path: str,
    base_cfg: dict[str, Any],
    holdout_per_group: int,
    bootstrap_resamples: int,
    generation_seeds: list[int],
    seed: int,
) -> dict[str, Any]:
    cfg = json.loads(json.dumps(base_cfg))
    params = cfg.setdefault("params", {})
    source_layer = int(best_candidate["source_layer"])
    window = int(best_candidate["window"])
    alpha = float(best_candidate["alpha"])

    cfg["experiment"] = CONFIRMATORY_EXPERIMENT
    cfg["run_name"] = (
        f"mistral_l{source_layer}_w{window}_a{_format_alpha(alpha)}_state_benchmark_v3_confirmatory"
    )
    cfg["seed"] = int(seed)
    params["source_layer"] = source_layer
    params["window"] = window
    params["holdout_per_group"] = int(holdout_per_group)
    params["generation_seeds"] = [int(x) for x in generation_seeds]
    params["bootstrap_resamples"] = int(bootstrap_resamples)
    params["interventions"] = [
        {"name": "away_alpha_best", "alpha": -alpha},
        {"name": "none", "alpha": 0.0},
        {"name": "toward_alpha_best", "alpha": alpha},
    ]
    params["control_name"] = "none"
    params["primary_prompt_mode"] = "recursive"
    params["control_prompt_mode"] = "baseline"
    decision = evaluate_promotion(best_candidate, min_score=float("-inf"), min_sign_matches=0)
    cfg["autogenerated_from"] = {
        "best_candidate_path": best_candidate_path,
        "source_layer": source_layer,
        "window": window,
        "alpha": alpha,
        "objective_score": decision["score"],
        "sign_match_count": decision["sign_match_count"],
    }
    return cfg


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a confirmatory v3 benchmark config from a targeted scan best candidate."
    )
    parser.add_argument("--best-candidate", required=True, type=Path)
    parser.add_argument("--base-config", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--holdout-per-group", type=int, default=12)
    parser.add_argument("--bootstrap-resamples", type=int, default=4000)
    parser.add_argument("--generation-seeds", nargs="+", type=int, default=[101, 202, 303, 404])
    parser.add_argument("--seed", type=int, default=314)
    parser.add_argument("--min-score", type=float, default=0.0)
    parser.add_argument("--min-sign-matches", type=int, default=3)
    args = parser.parse_args()

    best_candidate = json.loads(args.best_candidate.read_text())
    decision = evaluate_promotion(
        best_candidate,
        min_score=float(args.min_score),
        min_sign_matches=int(args.min_sign_matches),
    )
    if not decision["launched"]:
        print(json.dumps(decision))
        return 2

    cfg = build_confirmatory_config(
        best_candidate=best_candidate,
        best_candidate_path=str(args.best_candidate),
        base_cfg=json.loads(args.base_config.read_text()),
        holdout_per_group=int(args.holdout_per_group),
        bootstrap_resamples=int(args.bootstrap_resamples),
        generation_seeds=[int(x) for x in args.generation_seeds],
        seed=int(args.seed),
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                **decision,
                "output": str(args.output),
                "source_layer": cfg["params"]["source_layer"],
                "window": cfg["params"]["window"],
                "alpha": cfg["params"]["interventions"][-1]["alpha"],
            }
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
